sample/ContosoUniversity.EntityFrameworkCore.Store/Models/ErrorViewModel.cs
namespace ContosoUniversity.EntityFrameworkCore.Store.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

sample/ContosoUniversity.EntityFrameworkCore.Store/Models/Permissions.cs
namespace ContosoUniversity.EntityFrameworkCore.Store.Models
{
    public static class Permissions
    {
        public const string GradesRead = "grades.read";
        public const string GradesEdit = "grades.edit";
    }
}

sample/ContosoUniversity.EntityFrameworkCore.Store/Models/Policies.cs
namespace ContosoUniversity.EntityFrameworkCore.Store.Models
{
    public static class Policies
    {
        public const string ValidateGrades = "ValidateGrades";
    }
}

sample/ContosoUniversity.EntityFrameworkCore.Store/Models/Roles.cs
namespace ContosoUniversity.EntityFrameworkCore.Store.Models
{
    public static class Roles
    {
        public const string Custodian = nameof(Custodian);
        public const string Teacher = nameof(Teacher);
        public const string Substitute = nameof(Substitute);
        public const string Student = nameof(Student);
    }
}

sample/ContosoUniversity.EntityFrameworkCore.Store/Models/Tokens.cs
namespace ContosoUniversity.EntityFrameworkCore.Store.Models
{
    public class Tokens
    {
        public string AccessToken { get; set; }
        public string IdToken { get; set; }
    }
}

sample/ContosoUniversity.EntityFrameworkCore.Store/Controllers/AccountController.cs
using ContosoUniversity.Configuration.Store.Controllers;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ContosoUniversity.EntityFrameworkCore.Store.Controllers
{
    public class AccountController : Controller
    {
        [Authorize]
        public IActionResult Login()
        {
            return RedirectToAction(nameof(HomeController.Profile), "Home");
        }

        public ActionResult Logout()
        {
            return new SignOutResult(new[] { CookieAuthenticationDefaults.AuthenticationScheme, OpenIdConnectDefaults.AuthenticationScheme });
        }

        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

sample/ContosoUniversity.EntityFrameworkCore.Store/Controllers/GradesController.cs
using Balea.Authorization.Abac;
using ContosoUniversity.EntityFrameworkCore.Store.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ContosoUniversity.Configuration.Store.Controllers
{
    public class GradesController : Controller
    {
        [Authorize(Permissions.GradesRead)]
        public IActionResult Read()
        {
            return View();
        }

        [Authorize(Permissions.GradesEdit)]
        public IActionResult Edit()
        {
            return View();
        }
    }
}

sample/ContosoUniversity.EntityFrameworkCore.Store/Controllers/HomeController.cs
using System.Diagnostics;
using System.Threading.Tasks;
using ContosoUniversity.EntityFrameworkCore.Store.Infrastructure;
using ContosoUniversity.EntityFrameworkCore.Store.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ContosoUniversity.Configuration.Store.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Blog()
        {
            return View();
        }

        public IActionResult Teachers()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        [Authorize]
        public IActionResult Profile()
        {
            return View();
        }

        [AuthorizeRoles(nameof(Roles.Teacher), nameof(Roles.Substitute), nameof(Roles.Student))]
        public IActionResult Courses()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public async Task<IActionResult> Tokens()
        {
            var tokens = new Tokens
            {
                AccessToken = await HttpContext.GetTokenAsync("access_token"),
                IdToken = await HttpContext.GetTokenAsync("id_token")
            };

            return View(tokens);
        }
    }
}

sample/ContosoUniversity.EntityFrameworkCore.Store/Views/Grades/Edit.cshtml
<section class="ftco-section ftco-no-pt ftco-no-pb contact-section">
    <div class="container">
        <div class="row d-flex align-items-stretch no-gutters">
            <div class="col-md-6 p-4 p-md-5 order-md-last bg-light">
                <form action="#">
                    <div class="form-group">
                        <label>Student</label>
                        <select class="form-control">
                            <option>Perter Parker.</option>
                            <option>Mary Jane.</option>
                            <option>Harry Osborn.</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Subject</label>
                        <select class="form-control">
                            <option>Engineering Mathematics.</option>
                            <option>Electronic Circuits.</option>
                            <option>Logic Design.</option>
                            <option>Discrete Mathematical Structures.</option>
                            <option>Object-Oriented Programming With C++.</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Grade</label>
                        <select class="form-control">
                            <option>A+</option>
                            <option>A.</option>
                            <option>A-</option>
                            <option>B+</option>
                            <option>B</option>
                            <option>B-</option>
                            <option>C+</option>
                            <option>C</option>
                            <option>C-</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary py-3 px-5">Save</button>
                        <div asp-validation-summary="All"></div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

sample/ContosoUniversity.EntityFrameworkCore.Store/Views/Grades/Read.cshtml
@{
    ViewData["Title"] = "Blog";
}

<section class="hero-wrap hero-wrap-2" style="background-image: url('../../../images/bg_1.jpg');">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 ftco-animate text-center">
                <h1 class="mb-2 bread">View Grades</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Grades <i class="ion-ios-arrow-forward"></i></span></p>
            </div>
        </div>
    </div>
</section>
<section class="ftco-section contact-section">
    <div class="container">
        <div class="row d-flex contact-info">
            <div class="col-md-3 d-flex">
                <div class="bg-light align-self-stretch box p-4 text-center">
                    <h3 class="mb-4">Engineering Mathematics</h3>
                    <p>A+</p>
                </div>
            </div>
            <div class="col-md-3 d-flex">
                <div class="bg-light align-self-stretch box p-4 text-center">
                    <h3 class="mb-4">Data Structures With C.</h3>
                    <p>A</p>
                </div>
            </div>
            <div class="col-md-3 d-flex">
                <div class="bg-light align-self-stretch box p-4 text-center">
                    <h3 class="mb-4">Object-Oriented Programming With C++.</h3>
                    <p>B</p>
                </div>
            </div>
            <div class="col-md-3 d-flex">
                <div class="bg-light align-self-stretch box p-4 text-center">
                    <h3 class="mb-4">Databases</h3>
                    <p>A+</p>
                </div>
            </div>
        </div>
    </div>
</section>

sample/ContosoUniversity.EntityFrameworkCore.Store/Views/Grades/Validate.cshtml
<section class="ftco-section ftco-no-pt ftco-no-pb contact-section">
    <div class="container">
        <div class="row d-flex align-items-stretch no-gutters">
            <div class="col-md-6 p-4 p-md-5 order-md-last bg-light">
                <form asp-controller="Grades" asp-action="Validate">
                    <div class="form-group">
                        <label>Student</label>
                        <select class="form-control">
                            <option>Perter Parker.</option>
                            <option>Mary Jane.</option>
                            <option>Harry Osborn.</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Subject</label>
                        <select class="form-control">
                            <option>Engineering Mathematics.</option>
                            <option>Electronic Circuits.</option>
                            <option>Logic Design.</option>
                            <option>Discrete Mathematical Structures.</option>
                            <option>Object-Oriented Programming With C++.</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Grade</label>
                        <select class="form-control" name="value">
                            <option value="9">A+</option>
                            <option value="8">A.</option>
                            <option value="7">A-</option>
                            <option value="6">B+</option>
                            <option value="5">B</option>
                            <option value="4">B-</option>
                            <option value="3">C+</option>
                            <option value="2">C</option>
                            <option value="1">C-</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary py-3 px-5">Validate</button>
                        <div asp-validation-summary="All"></div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

sample/ContosoUniversity.EntityFrameworkCore.Store/Views/Home/CloseDoor.cshtml
@{
    ViewData["Title"] = "CloseDoor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Door closed!</h1>

sample/ContosoUniversity.EntityFrameworkCore.Store/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}

<section class="hero-wrap hero-wrap-2" style="background-image: url('../../../images/bg_1.jpg');">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 ftco-animate text-center">
                <h1 class="mb-2 bread">Contact Us</h1>
                <p class="breadcrumbs"><span class="mr-2"><a asp-controller="Home" asp-action="Index">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Contact <i class="ion-ios-arrow-forward"></i></span></p>
            </div>
        </div>
    </div>
</section>

<section class="ftco-section contact-section">
    <div class="container">
        <div class="row d-flex contact-info">
            <div class="col-md-3 d-flex">
                <div class="bg-light align-self-stretch box p-4 text-center">
                    <h3 class="mb-4">Address</h3>
                    <p>198 West 21th Street, Suite 721 New York NY 10016</p>
                </div>
            </div>
            <div class="col-md-3 d-flex">
                <div class="bg-light align-self-stretch box p-4 text-center">
                    <h3 class="mb-4">Contact Number</h3>
                    <p><a href="tel://1234567920">+ 1235 2355 98</a></p>
                </div>
            </div>
            <div class="col-md-3 d-flex">
                <div class="bg-light align-self-stretch box p-4 text-center">
                    <h3 class="mb-4">Email Address</h3>
                    <p><a href="mailto:info@yoursite.com">info@yoursite.com</a></p>
                </div>
            </div>
            <div class="col-md-3 d-flex">
                <div class="bg-light align-self-stretch box p-4 text-center">
                    <h3 class="mb-4">Website</h3>
                    <p><a href="#">yoursite.com</a></p>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="ftco-section ftco-no-pt ftco-no-pb contact-section">
    <div class="container">
        <div class="row d-flex align-items-stretch no-gutters">
            <div class="col-md-12 p-4 p-md-5 order-md-last bg-light">
                <form action="#">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Your Name">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Your Email">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Subject">
                    </div>
                    <div class="form-group">
                        <textarea name="" id="" cols="30" rows="7" class="form-control" placeholder="Message"></textarea>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

sample/ContosoUniversity.EntityFrameworkCore.Store/Views/Home/Courses.cshtml
@{
    ViewData["Title"] = "Blog";
}

<section class="hero-wrap hero-wrap-2" style="background-image: url('../../../images/bg_1.jpg');">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 ftco-animate text-center">
                <h1 class="mb-2 bread">Courses</h1>
                <p class="breadcrumbs"><span class="mr-2"><a asp-controller="Home" asp-action="Index">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Courses <i class="ion-ios-arrow-forward"></i></span></p>
            </div>
        </div>
    </div>
</section>

<section class="ftco-section">
    <div class="container-fluid px-4">
        <div class="row">
            <div class="col-md-3 course ftco-animate">
                <div class="img" style="background-image: url(../../../images/course-1.jpg);"></div>
                <div class="text pt-4">
                    <p class="meta d-flex">
                        <span><i class="icon-user mr-2"></i>Mr. Khan</span>
                        <span><i class="icon-table mr-2"></i>10 seats</span>
                        <span><i class="icon-calendar mr-2"></i>4 Years</span>
                    </p>
                    <h3><a href="#">Software Engineering</a></h3>
                    <p>Separated they live in. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country</p>
                    <Balea Permissions="Grades.Read">
                        <p><a asp-controller="Grades" asp-action="Read" class="btn btn-primary">View Grades</a></p>
                    </Balea>
                    <Balea Permissions="Grades.Edit">
                        <p><a asp-controller="Grades" asp-action="Edit" class="btn btn-primary">Edit Grades</a></p>
                    </Balea>
                    <Balea Permissions="Grades.Edit">
                        <p><a asp-controller="Grades" asp-action="Validate" class="btn btn-primary">Validate Grades</a></p>
                    </Balea>
                </div>
            </div>
            <div class="col-md-3 course ftco-animate">
                <div class="img" style="background-image: url(../../../images/course-2.jpg);"></div>
                <div class="text pt-4">
                    <p class="meta d-flex">
                        <span><i class="icon-user mr-2"></i>Mr. Khan</span>
                        <span><i class="icon-table mr-2"></i>10 seats</span>
                        <span><i class="icon-calendar mr-2"></i>4 Years</span>
                    </p>
                    <h3><a href="#">Game Engineering</a></h3>
                    <p>Separated they live in. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country</p>
                    <Balea Permissions="Grades.Read">
                        <p><a asp-controller="Grades" asp-action="Read" class="btn btn-primary">View Grades</a></p>
                    </Balea>
                    <Balea Permissions="Grades.Edit">
                        <p><a asp-controller="Grades" asp-action="Edit" class="btn btn-primary">Edit Grades</a></p>
                    </Balea>
                    <Balea Permissions="Grades.Edit">
                        <p><a asp-controller="Grades" asp-action="Validate" class="btn btn-primary">Validate Grades</a></p>
                    </Balea>
                </div>
            </div>
            <div class="col-md-3 course ftco-animate">
                <div class="img" style="background-image: url(../../../images/course-3.jpg);"></div>
                <div class="text pt-4">
                    <p class="meta d-flex">
                        <span><i class="icon-user mr-2"></i>Mr. Khan</span>
                        <span><i class="icon-table mr-2"></i>10 seats</span>
                        <span><i class="icon-calendar mr-2"></i>4 Years</span>
                    </p>
                    <h3><a href="#">Data Engineering</a></h3>
                    <p>Separated they live in. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country</p>
                    <Balea Permissions="Grades.Read">
                        <p><a asp-controller="Grades" asp-action="Read" class="btn btn-primary">View Grades</a></p>
                    </Balea>
                    <Balea Permissions="Grades.Edit">
                        <p><a asp-controller="Grades" asp-action="Edit" class="btn btn-primary">Edit Grades</a></p>
                    </Balea>
                    <Balea Permissions="Grades.Edit">
                        <p><a asp-controller="Grades" asp-action="Validate" class="btn btn-primary">Validate Grades</a></p>
                    </Balea>
                </div>
            </div>
            <div class="col-md-3 course ftco-animate">
                <div class="img" style="background-image: url(../../../images/course-4.jpg);"></div>
                <div class="text pt-4">
                    <p class="meta d-flex">
                        <span><i class="icon-user mr-2"></i>Mr. Khan</span>
                        <span><i class="icon-table mr-2"></i>10 seats</span>
                        <span><i class="icon-calendar mr-2"></i>4 Years</span>
                    </p>
                    <h3><a href="#">AI Engineering</a></h3>
                    <p>Separated they live in. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country</p>
                    <Balea Permissions="Grades.Read">
                        <p><a asp-controller="Grades" asp-action="Read" class="btn btn-primary">View Grades</a></p>
                    </Balea>
                    <Balea Permissions="Grades.Edit">
                        <p><a asp-controller="Grades" asp-action="Edit" class="btn btn-primary">Edit Grades</a></p>
                    </Balea>
                    <Balea Permissions="Grades.Edit">
                        <p><a asp-controller="Grades" asp-action="Validate" class="btn btn-primary">Validate Grades</a></p>
                    </Balea>
                </div>
            </div>

            <div class="col-md-3 course ftco-animate">
                <div class="img" style="background-image: url(../../../images/course-5.jpg);"></div>
                <div class="text pt-4">
                    <p class="meta d-flex">
                        <span><i class="icon-user mr-2"></i>Mr. Khan</span>
                        <span><i class="icon-table mr-2"></i>10 seats</span>
                        <span><i class="icon-calendar mr-2"></i>4 Years</span>
                    </p>
                    <h3><a href="#">Computer Engineering</a></h3>
                    <p>Separated they live in. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country</p>
                    <Balea Permissions="Grades.Read">
                        <p><a asp-controller="Grades" asp-action="Read" class="btn btn-primary">View Grades</a></p>
                    </Balea>
                    <Balea Permissions="Grades.Edit">
                        <p><a asp-controller="Grades" asp-action="Edit" class="btn btn-primary">Edit Grades</a></p>
                    </Balea>
                    <Balea Permissions="Grades.Edit">
                        <p><a asp-controller="Grades" asp-action="Validate" class="btn btn-primary">Validate Grades</a></p>
                    </Balea>
                </div>
            </div>
            <div class="col-md-3 course ftco-animate">
                <div class="img" style="background-image: url(../../../images/course-6.jpg);"></div>
                <div class="text pt-4">
                    <p class="meta d-flex">
                        <span><i class="icon-user mr-2"></i>Mr. Khan</span>
                        <span><i class="icon-table mr-2"></i>10 seats</span>
                        <span><i class="icon-calendar mr-2"></i>4 Years</span>
                    </p>
                    <h3><a href="#">IoT Engineering</a></h3>
                    <p>Separated they live in. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country</p>
                    <Balea Permissions="Grades.Read">
                        <p><a asp-controller="Grades" asp-action="Read" class="btn btn-primary">View Grades</a></p>
                    </Balea>
                    <Balea Permissions="Grades.Edit">
                        <p><a asp-controller="Grades" asp-action="Edit" class="btn btn-primary">Edit Grades</a></p>
                    </Balea>
                    <Balea Permissions="Grades.Edit">
                        <p><a asp-controller="Grades" asp-action="Validate" class="btn btn-primary">Validate Grades</a></p>
                    </Balea>
                </div>
            </div>
            <div class="col-md-3 course ftco-animate">
                <div class="img" style="background-image: url(../../../images/course-7.jpg);"></div>
                <div class="text pt-4">
                    <p class="meta d-flex">
                        <span><i class="icon-user mr-2"></i>Mr. Khan</span>
                        <span><i class="icon-table mr-2"></i>10 seats</span>
                        <span><i class="icon-calendar mr-2"></i>4 Years</span>
                    </p>
                    <h3><a href="#">DevOps Engineering</a></h3>
                    <p>Separated they live in. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country</p>
                    <Balea Permissions="Grades.Read">
                        <p><a asp-controller="Grades" asp-action="Read" class="btn btn-primary">View Grades</a></p>
                    </Balea>
                    <Balea Permissions="Grades.Edit">
                        <p><a asp-controller="Grades" asp-action="Edit" class="btn btn-primary">Edit Grades</a></p>
                    </Balea>
                    <Balea Permissions="Grades.Edit">
                        <p><a asp-controller="Grades" asp-action="Validate" class="btn btn-primary">Validate Grades</a></p>
                    </Balea>
                </div>
            </div>
            <div class="col-md-3 course ftco-animate">
                <div class="img" style="background-image: url(../../../images/course-8.jpg);"></div>
                <div class="text pt-4">
                    <p class="meta d-flex">
                        <span><i class="icon-user mr-2"></i>Mr. Khan</span>
                        <span><i class="icon-table mr-2"></i>10 seats</span>
                        <span><i class="icon-calendar mr-2"></i>4 Years</span>
                    </p>
                    <h3><a href="#">QA Engineering</a></h3>
                    <p>Separated they live in. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country</p>
                    <Balea Permissions="Grades.Read">
                        <p><a asp-controller="Grades" asp-action="Read" class="btn btn-primary">View Grades</a></p>
                    </Balea>
                    <Balea Permissions="Grades.Edit">
                        <p><a asp-controller="Grades" asp-action="Edit" class="btn btn-primary">Edit Grades</a></p>
                    </Balea>
                </div>
            </div>
        </div>
    </div>
</section>

sample/ContosoUniversity.EntityFrameworkCore.Store/Views/Home/EditGrades.cshtml
@{
    ViewData["Title"] = "EditGrades";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>EditGrades</h1>

<form>
    <div class="form-group">
        <label for="exampleFormControlInput1">Name</label>
        <input type="text" class="form-control" id="exampleFormControlInput1" value="Mark Otto">
    </div>
    <div class="form-group">
        <label for="exampleFormControlSelect1">Grade</label>
        <select class="form-control" id="exampleFormControlSelect1">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
            <option>6</option>
            <option>7</option>
            <option>8</option>
            <option>9</option>
            <option>10</option>
        </select>
    </div>
    <div class="form-group">
        <label for="exampleFormControlTextarea1">Observations:</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
    </div>
</form>

sample/ContosoUniversity.EntityFrameworkCore.Store/Views/Home/OpenDoor.cshtml
@{
    ViewData["Title"] = "OpenDoor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Door opened!</h1>

sample/ContosoUniversity.EntityFrameworkCore.Store/Views/Home/Private.cshtml
@{
    ViewData["Title"] = "Private area";
}
<h1>@ViewData["Title"]</h1>

<p>Use this page to detail your personal information.</p>

@foreach (var identity in User.Identities)
{
    <h3>Authentication scheme: @identity.AuthenticationType</h3>
    <ul>
        @foreach (var claim in identity.Claims)
        {
            <li>Claim: @claim.Type - @claim.Value</li>
        }
    </ul>
}

<h3>Roles and permissions</h3>

<div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
    <h5 class="card-header">Teachers</h5>
    <div class="card-body">
        <p class="card-text">Teachers can view and edit grades.</p>
        <a class="btn btn-light" asp-area="" asp-controller="Home" asp-action="ViewGrades">View grades</a>
        <a class="btn btn-light" asp-area="" asp-controller="Home" asp-action="EditGrades">Edit grades</a>
    </div>
</div>


<div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
    <div class="card-header">Substitutes</div>
    <div class="card-body">
        <p class="card-text">Substitutes can view and edit grades when a teacher delegate his/her permissions.</p>
        <a class="btn btn-light" asp-area="" asp-controller="Home" asp-action="ViewGrades">View grades</a>
        <a class="btn btn-light" asp-area="" asp-controller="Home" asp-action="EditGrades">Edit grades</a>
    </div>
</div>

<div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
    <div class="card-header">Custodians</div>
    <div class="card-body">
        <p class="card-text">Custodians open and close doors.</p>
        <a class="btn btn-light" asp-area="" asp-controller="Home" asp-action="OpenDoor">Open doors</a>
        <a class="btn btn-light" asp-area="" asp-controller="Home" asp-action="CloseDoor">Close doors</a>
    </div>
</div>

sample/ContosoUniversity.EntityFrameworkCore.Store/Views/Home/Profile.cshtml
@{
    ViewData["Title"] = "Profile";
}

<section class="ftco-section ftco-no-pt ftc-no-pb">
    <div class="container">
        <div class="row d-flex">
            <div class="col-md-12 wrap-about py-5 pr-md-4 ftco-animate">
                @foreach (var identity in User.Identities)
                {
                    <h2 class="mb-4">Authentication scheme: @identity.AuthenticationType</h2>
                    <ul>
                        @foreach (var claim in identity.Claims)
                        {
                            <li><p><strong>Claim Type:</strong> @claim.Type - <strong>Claim Value:</strong> @claim.Value</p></li>
                        }
                    </ul>
                }
            </div>
        </div>
    </div>
</section>

sample/ContosoUniversity.EntityFrameworkCore.Store/Views/Home/Tokens.cshtml
@model Tokens

@{
    ViewData["Title"] = "Profile";
}

<section class="ftco-section ftco-no-pt ftc-no-pb">
    <div class="container">
        <div class="row d-flex">
            <div class="col-md-12 wrap-about py-5 pr-md-4 ftco-animate">
                <h1>Access Token</h1>
                <p>@Model.AccessToken</p>
                <h1>Id Token</h1>
                <p>@Model.IdToken</p>
            </div>
        </div>
    </div>
</section>